# Generated by Django 4.1.2 on 2024-03-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
            ],
        ),
    ]
