# Generated by Django 4.1.2 on 2024-03-27 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registration_filled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
