# Generated by Django 4.1.2 on 2024-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
